# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addUserWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddUserWindow(object):
    def setupUi(self, AddUserWindow):
        AddUserWindow.setObjectName("AddUserWindow")
        AddUserWindow.resize(556, 600)
        self.centralwidget = QtWidgets.QWidget(AddUserWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTitleWindow = QtWidgets.QLabel(self.centralwidget)
        self.labelTitleWindow.setGeometry(QtCore.QRect(10, 20, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelTitleWindow.setFont(font)
        self.labelTitleWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelTitleWindow.setObjectName("labelTitleWindow")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 370, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(13, 103, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 110, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 170, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 290, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 230, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        AddUserWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddUserWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 23))
        self.menubar.setObjectName("menubar")
        AddUserWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddUserWindow)
        self.statusbar.setObjectName("statusbar")
        AddUserWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AddUserWindow)
        QtCore.QMetaObject.connectSlotsByName(AddUserWindow)

    def retranslateUi(self, AddUserWindow):
        _translate = QtCore.QCoreApplication.translate
        AddUserWindow.setWindowTitle(_translate("AddUserWindow", "ДОБАВИТЬ ПОЛЬЗОВАТЕЛЯ"))
        self.labelTitleWindow.setText(_translate("AddUserWindow", "<html><head/><body><p align=\"center\">Панель создания нового пользователя</p></body></html>"))
        self.pushButton_7.setText(_translate("AddUserWindow", "Добавить сотрудника"))
        self.lineEdit.setPlaceholderText(_translate("AddUserWindow", "введите имя сотрудника"))
        self.lineEdit_2.setPlaceholderText(_translate("AddUserWindow", "введите логин сотрудника"))
        self.lineEdit_3.setPlaceholderText(_translate("AddUserWindow", "введите должность сотрудника"))
        self.lineEdit_5.setPlaceholderText(_translate("AddUserWindow", "введите парольдля доступа"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddUserWindow = QtWidgets.QMainWindow()
    ui = Ui_AddUserWindow()
    ui.setupUi(AddUserWindow)
    AddUserWindow.show()
    sys.exit(app.exec_())
